### PR TITLE
Fix issue #3

### LINKED ISSUE #3: SELECT X, AGGREGATE_METRIC FROM STREAM(...) returns only AGGREGATE_METRIC
Supplying X should be an error

### PR DESCRIPTION
**Pull request by hbxie**
Fix #3.

### CODE REVIEW

File: src/main/java/com/yahoo/bullet/bql/extractor/AggregationExtractor.java [hunk 1]
```diff
@@ -206,12 +208,18 @@ public Aggregation extractRaw(Optional<Long> size) throws NullPointerException {
...
+        for (Expression selectField : selectFields) {
+            if (selectField instanceof FunctionCall) {
+                functions.add(selectField);
+            } else {
+                if (!groupByFields.contains(selectField)) {
+                    throw new ParsingException("Select field " + selectField.toFormatlessString()  + " should be a grouping function or in GROUP BY clause");
+                }
+            }
+        }
+        Collections.sort(functions, Expression::compareTo);
```
Comment (akshaisarma) [inline src/main/java/com/yahoo/bullet/bql/extractor/AggregationExtractor.java]: Why do we need to sort it?

File: src/main/java/com/yahoo/bullet/bql/extractor/AggregationExtractor.java [hunk 2]
```diff
@@ -206,12 +208,18 @@ public Aggregation extractRaw(Optional<Long> size) throws NullPointerException {
...
-                .collect(Collectors.toList());
-
+    private Map<String, Object> getGroupAttributes(Set<Expression> selectFields, Set<Expression> groupByFields) {
+        List<Expression> functions = new ArrayList<>();
+        for (Expression selectField : selectFields) {
+            if (selectField instanceof FunctionCall) {
+                functions.add(selectField);
+            } else {
+                if (!groupByFields.contains(selectField)) {
+                    throw new ParsingException("Select field " + selectField.toFormatlessString()  + " should be a grouping function or in GROUP BY clause");
```
Comment (akshaisarma) [inline src/main/java/com/yahoo/bullet/bql/extractor/AggregationExtractor.java]: or *be* in GROUP BY clause
